# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e2253d94f44b830840da1360f71602515a099d440579b6df8268291d9884f89f6a454360b547c66d221151153493cc06db7c9ea3744c98d6535d316dccab8754

test:
  secret_key_base: 61269c358775732b8aaa242f22c8a4d28d07a4484c5dc1ab165fcba15a2420f8169a22e48dd34ff591b97803ed9e102e480da9b3de249ef4f8a884fd12f8edcb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
